[project]
name = "OsTool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.10.4",
    "pygobject>=3.50.0",
]

[dependency-groups]
dev = [
    "pygobject-stubs>=2.12.0",
]
